version: "3.9"
services:
  backend:
    build:
       context: ./backend
       dockerfile: Dockerfile
    image: project-backend:latest
    container_name: backend
    ports:
       - "8080:8080"
    environment:
       - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
     build:
       context: ./frontend
       dockerfile: Dockerfile
     image: project-frontend:latest
     container_name: frontend
     ports:
        - "80:80"
     depends_on:
       backend:
          condition: service_healthy
      
      