name: Maven Build

on:
  push:
    branches:
    - main
    - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up JDK 
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3. Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4. Build Spring Boot project
    - name: Build with Maven
      working-directory: backend
      run: mvn clean package

    # 5. Archive the generated JAR
    - name: Archive JAR
      uses: actions/upload-artifact@v4
      with:
        name: springboot-jar
        path: backend/target/*.jar